module.exports = {
  // ==========================================
  // SECTION A: PRELIMINARY EXAMINATION
  // ==========================================
  1: "Pre-historic culture and various ancient historic sites of Rajasthan and their importance",
  2: "Major Dynasties of Rajasthan & their achievements",
  3: "Administrative and revenue system of major dynasties in Rajasthan",
  4: "Political awakening and 1857 Revolt in Rajasthan",
  5: "Peasant, tribal, and Praja Mandal movements in Rajasthan",
  6: "Integration of Rajasthan: The seven stages of state formation",
  7: "Architectural heritage of Rajasthan: Forts, palaces, temples, stepwells, paintings & handicrafts",
  8: "Performing arts of Rajasthan: Folk music, instruments, folk dances & folk dramas",
  9: "Rajasthani dialects, language, and prominent historical literature",
  10: "Religious sects, saints, folk deities & social customs/fairs of Rajasthan",
  11: "Cultural Foundations of India - Indus & Vedic Age; Religious ideas of 6th Century BC",
  12: "Achievements of prominent rulers of major dynasties: Maurya, Kushan, Satavahan, Gupta, Chalukya, Pallava and Chola",
  13: "Art, Architecture, Scientific Development & Indian Knowledge/Value System in Ancient India",
  14: "Medieval India: Delhi Sultanate and Mughal Empire - administration, art, architecture & literature",
  15: "Medieval India: Bhakti movement, Sufism and cultural synthesis",
  16: "Modern India: Socio-religious reform movements in 19th & 20th centuries",
  17: "Modern India: Indian National Movement - 1857 Revolt, early phase, Swadeshi, Gandhian era & freedom struggle",
  18: "Post-independence India: Integration of princely states & linguistic reorganization of states",
  19: "World Physical Geography: Major landforms, climate types, interior of Earth & earthquakes/volcanoes",
  20: "World Geography: Environmental issues, global agriculture types, major industrial regions & transport",
  21: "India Physical Geography: Physiographic divisions, major rivers, lakes & drainage systems",
  22: "India Geography: Climate systems, monsoons, forest types & soil classifications",
  23: "India Resources: Major minerals, energy resources, major industries & population demographics",
  24: "India Economy Geography: Agriculture, major crops, irrigation systems & agro-based industries",
  25: "Rajasthan Physical: Physiographic divisions, geological structures & climate classification",
  26: "Rajasthan Drainage: Major river basins, lakes & water conservation systems",
  27: "Rajasthan Resources: Natural vegetation, forest coverage, wildlife sanctuaries & biodiversity",
  28: "Rajasthan Soils: Soil types, distribution, erosion issues & conservation methods",
  29: "Rajasthan Minerals: Metallic & non-metallic minerals, distribution & major mining zones",
  30: "Rajasthan Demographics: Population distribution, growth, literacy, sex-ratio, agriculture, livestock, irrigation & tourism",
  31: "Constitutional Development & Philosophy: Preamble, Salient Features, Fundamental Rights, Duties & DPSP",
  32: "Union Government: Executive, Parliament, Supreme Court & Judicial Activism",
  33: "Constitutional & Non-Constitutional Bodies: Election Commission, CAG, UPSC, NHRC, NITI Aayog",
  34: "Indian Federalism: Centre-State relations, coalition politics & national integration",
  35: "Public Policy & Rights: Citizen charters, Right to Information (RTI), Lokpal & Social Audit",
  36: "State Government: Governor, Chief Minister, Council of Ministers & Chief Secretary",
  37: "Judiciary: Rajasthan High Court and subordinate judiciary",
  38: "State Commissions: RPSC, State Election/Information Commission & Lokayukta",
  39: "Local Self-Government: Panchayati Raj Institutions & Urban Local Bodies in Rajasthan",
  40: "Administrative Governance: District administration, citizen-centric services, RTPS Act & Rajasthan Sampark",
  41: "Basic Economic Concepts: National Income, inflation, monetary policy, fiscal policy & SDGs",
  42: "Public Finance: Taxation system, GST, union budget & fiscal federalism",
  43: "Economic Planning & Development: Achievements, human development index (HDI), poverty & employment",
  44: "Major Sectors of Indian Economy: Agricultural reforms, industrial policies, infrastructure & services sector",
  45: "Welfare Initiatives: Social security schemes, financial inclusion & food security",
  46: "Rajasthan SDP & Growth: State domestic product, macro-economic overview & state budget trends",
  47: "Rajasthan Agriculture: Agricultural production, cropping patterns, land reforms & cooperative societies",
  48: "Rajasthan Industry & Infrastructure: MSMEs, industrial parks, RIICO, power generation & road networks",
  49: "Rajasthan Services & Tourism: Tourism sector, heritage hotels, handicrafts export & state revenue",
  50: "Rajasthan Welfare Schemes: Social security pensions, rural employment & weaker sections welfare",
  51: "Everyday Science: Basic physics, chemistry, cell biology & human diseases",
  52: "Information & Communication Technology & Biotechnology: AI, Big Data, IoT & Genetic Engineering",
  53: "Space & Defence Technology: Indian space program (ISRO) & defence systems (DRDO)",
  54: "Biotechnology & Nanotechnology: Applications, genetic engineering, cloning & nanomaterials",
  55: "Environmental Science & Agriculture: Biodiversity, climate change, ecosystems & Rajasthan agriculture context",
  56: "Logical & Analytical Reasoning: Statements, arguments, assumptions & conclusions",
  57: "Mental Ability: Coding-Decoding, Number/Letter Sequences & Direction Tests",
  58: "Basic Numeracy & Statistics: Averages, percentage, interest, ratios, probability & mean/median/mode",
  59: "Data Interpretation: Bar charts, pie charts, tables, line graphs & data sufficiency",
  60: "State Level Current Affairs: Major socio-political events, schemes & personalities in news in Rajasthan",
  61: "National Level Current Affairs: Major national events, appointments, policies & bilateral agreements",
  62: "International Level Current Affairs: Global summits, world organizations & sports tournaments",

  // ==========================================
  // SECTION B: MAINS EXAMINATION
  // ==========================================
  101: "Part A - History, Art, Culture, Literature, Tradition and Heritage of Rajasthan",
  102: "Part B - Indian History & Culture",
  103: "Part C - History of Modern World (up to 1991 A.D.)",
  104: "Part A - Indian Economy",
  105: "Part B - World Economy",
  106: "Part C - Economy of Rajasthan",
  107: "Part A - Sociology",
  108: "Part B - Management",
  109: "Part C - Accounting & Auditing",
  110: "Administrative Ethics & values, Rit/Rin, integrity, Geeta & Gandhian ethics, AI vs Conscience",
  111: "Physics, Chemistry, Cell Biology, Biotech, Computer Science, Space/Defence, Quantum computing",
  112: "World interior, Physical features, Climate, India physiography, Rajasthan geology & demographics",
  113: "Constitution, Union/State Executive, SC/HC, Party systems, Rajasthan Polity, Foreign Policy, G-20, QUAD",
  114: "Evolution, NPA, NPM, Organisation principles, Personnel admin, comparative admin, Rajasthan admin",
  115: "Emotional Intelligence, RAISEC Model, RTI/IT/DV/POSH/POCSO Acts, Land Revenue, BNS/BNSS 2023",
  116: "Part A Grammar (Prefix, Suffix, confusing words, corrections, idioms, admin terms)",
  117: "Part B & C (Precis, elaboration, translation formatting)",
  118: "Part A Grammar & Usage (Prepositions, parts of speech, phrasal verbs, one-word substitutes)",
  119: "Parts B & C (Comprehension tracking, sentence translation formatting)",
  120: "Structured thematic essay buckets (Heritage, Society, Science, Economy, Disasters, Rajasthan Tourism)"
};
